### ISSUE TITLE
Running the program with SNU601 scATAC-seq data gives different result

### ISSUE THREAD

**Issue by wjhlang** [colomemaria/epiAneufinder#18]
I am trying to replicate the experiment in the paper and ran the program using the SNU601 bam file from “[PRJNA674903](https://www.ncbi.nlm.nih.gov/sra?linkname=bioproject_sra_all&from_uid=674903)”. I am getting different results from the paper: more specifically, I do not see any cell with deletions in the middle of chr4, instead only at the start and end of chr4. Would it be possible for you to provide the specific parameters used for that result in the paper? I am interested in the cell names of those cells with deletion in the middle of chr4. It would be awesome if you could point me to where I could get these cell names from the generated results.
![Karyogram](https://github.com/colomemaria/epiAneufinder/assets/56660809/ed1ed0ab-9ef3-4a72-b9d3-dd4750dbb64e)

Thanks!

**Comment by thek71** [comment]
Hi Jason,

epiAneufinder expects to get one bam file per cell, or the fragments file for the whole run.
In the paper we used the fragments file, that was created by CellRanger.
What I would propose is to do the same, as it looks from the plot that you attached (if I understand it correctly) that you had as input the whole bam file. In this case it was treated as one cell.
For the parameters that we used, you can just use the default ones, they are the same.
We have pushed a new version of the software, with some additional functions that might be useful to you, like extracting specific clusters from the results.
If you want to get the cells that have a specific CNV location, you can use the results table, filter for the windows that you are interested and get the cell ids form there.

I hope that helps,
Katia

**Comment by wjhlang** [comment]
Hi Katia,

Thanks for the response! I have been trying to generate the fragment file using CellRanger, did you use cellranger-atac count for that matter? And if so, for the required fastq files, were the ones available in SRA sufficient or did you use the mkfastq function to generate the FASTQs? Would it be possible for you to share the fragment files? 

My apologies for all the questions, thank you so much!

Best,
Jason

**Comment by thek71** [comment]
Hi Jason,

we downloaded the fastq files from the SRA acrchive using the sartoolkit. And then cellranger-atac for the mapping and generation of the fragments file. Since the data are public I don't see a problem with sharing them.
The question is how to share. Do you have a file server that we can upload the data?

Thinking about it, another option would be to split the bam file that you have to several bam files, one per cell.
Here you can find instructions on how to do that ([https://kb.10xgenomics.com/hc/en-us/articles/360022448251-How-to-filter-the-BAM-file-produced-by-10x-pipelines-with-a-list-of-barcodes]).
Keep in mind that the number of file that will be created will be extremely high, due the many cells of the library.

Please tell me how you want to go about it.

Bset,
Katia

**Comment by wjhlang** [comment]
Hi Katia,

I actually just realized that as well and was trying the subset-bam function. Thanks for the suggestion! 
It would be awesome if you could share the fragment files, do you use Globus? It could be used as a validation and would be extremely helpful.

Again, appreciate the help and fast response!

Best,
Jinhao

**Comment by thek71** [comment]
Hi Jason,

I just wanted to check if you have managed to use the dataset. 
We don't use Globusin the lab, but if you still need the fragments maybe we can arrange something.

Best,
Katia

**Comment by wjhlang** [comment]
Hi Katia, 

Yes, I managed to pull out the fragments, thanks for the advice!

Best,
Jason
