### ISSUE TITLE
Size of chr2 and chr3 incredibly small for mouse data

### ISSUE THREAD

**Issue by Urja25** [colomemaria/epiAneufinder#19]
Hi,

when I run epiAneufinder on mouse data, I get a karyogram with very small sizes for chr2 and chr3 especially amongst other chromosomes. Could you help me correct the sizes?

e.g. 
<img width="1440" alt="Screen Shot 2024-03-06 at 3 24 49 PM" src="https://github.com/colomemaria/epiAneufinder/assets/135853774/1d002c28-796d-4013-9d3d-0ebbfcfd4571">

Thanks a lot!

**Comment by thek71** [comment]
Hi,

I think that what happens is that many bins in chr2 and 3 are filtered out due to lack of coverage.
If you are running epiAneufinder with default settings, then bins for which 85% of the cells have no signal are filtered out.
To verify that you can check on the results.tsv file and see for how many bins in the chromosomes 2 and 3 there is CNV information. Only these bins are plotted.

Best,
Katia
