### ISSUE TITLE
Discussion: universal chr6 copy number gain

### ISSUE THREAD

**Issue by bj-chen** [colomemaria/epiAneufinder#23]
Dear epiAneufinder team,

Thank you for your excellent work and for providing the community with this wonderful package. I have run epiAneufinder on our scATAC-seq dataset comprising 20 donors from both healthy and disease groups. I observed what appears to be a universal copy number gain on chromosome 6 across almost all 20 donors. To validate this finding, I tested a publicly available scATAC-seq dataset from an ovarian cancer patient, and the chromosome 6 copy number gain was still present.

I would greatly appreciate your input on whether this chromosome 6 copy number gain could be attributed to a technical bias or if you believe these are true copy number alterations. Your expertise and insights would be invaluable in interpreting these results accurately. Thank you in advance for your assistance.

Attached please find the karyogram plot of the ovarian cancer sample; the red band on chr6 is observed in almost all samples that I've tested.

With regards,
Bei Jun

![karyogram_3533EL](https://github.com/colomemaria/epiAneufinder/assets/8231793/32cbcd26-4888-49bc-9354-881735b4c6be)

**Comment by thek71** [comment]
Hi Bei Jun,

thank you for your kind words.
Regarding the issue that you have with chromosome 6, we have not seen it as a general bias.
We have analysed several datasets both for the publication and for other projects.
I went back to all of them and so far we have indeed seen the same band in chromosome 6 in only one other dataset, which has two diploid samples, one PBMC sample and one of bone marrow. You can find these samples in supplemental figure 7 of the publication.
We considered is to be some kind of noise, probably caused by high transcriptional activity, and thus openness, in the genes found in that area of chromosome 6, like for example HLA-A gene that is located there. 
If you have scRNA data from the same samples I would suggest to check the expression levels of the genes in the area of the proposed CNVs.
Another possibility is some type of bias of the sequencing protocol. That was also another thought we had when we all also saw the same patterns, given that it was only in one dataset with diverse tissues/cell types.
In general, since you find it consistently in all these samples and the profile resembles what we also noticed, I would consider it a false positive, unless additional evidence can be found.

I hope I helped.

Best,
Katia

**Comment by bj-chen** [comment]
Thank you Katia for taking the time to investigate this issue and provide a detailed response. I really appreciate your help in suggesting possible causes for this observation. As you recommended, I will look into the expression levels of genes on chromosome 6 and also check the sequencing protocol. 

With regards,
Bei Jun
