### ISSUE TITLE
Recommendations for window size parameter

### ISSUE THREAD

**Issue by clee700** [colomemaria/epiAneufinder#29]
Hello! Thank you for making such a useful tool. I was looking into the window size parameter, and wondering if you have any guidelines about how to set it. 
For example, if I make the window size smaller, would this give me higher resolution in detecting smaller changes in copy number? 
Thank you!
Christy

**Comment by thek71** [comment]
Hi Christie,

you can of course have a smaller window size. We use 100Kb in the paper because after trying different sizes it gave the best results for the samples that we have.
But we have also tested it at 10Kb.
The user can and should adapt this parameter if there is an expectation for smaller CNVs.
Keep in mind that the running time will be considerably increased.
Best regards,
Katia

**Comment by thek71** [comment]
Hi Christy,

I think we answered your question and I will close the issue.
If you have anything else to ask, feel free any time.

Best,
Katia
