### ISSUE TITLE
Issue related to 'zero windows remain' 

### ISSUE THREAD

**Issue by Krithika-Bhuvan** [colomemaria/epiAneufinder#33]
Hello, I'm trying out EpiAneufinder with some different settings based on our snMultiome fragment data
* windowSize = 1e5
* minFrags = 500
* k=4

It turns out that while the code seems to be running for some of my samples, for a few others it errors out. Based on the logs it seems like 0 windows remain after a filtering step.

Any idea why this would be happening and how I could be correcting ? Thank you

**Logs:**
```
[1] "Count matrix with 8160 cells and 26088 windows has been generated and will be saved as count_summary.rds"
[1] "Filtering empty windows, 0 windows remain."
```

**Error message**

```
Subtracting Blacklist...
Adding Nucleotide Information...
1 of 22
2 of 22
3 of 22
4 of 22
5 of 22
6 of 22
7 of 22
8 of 22
9 of 22
10 of 22
11 of 22
12 of 22
13 of 22
14 of 22
15 of 22
16 of 22
17 of 22
18 of 22
19 of 22
20 of 22
21 of 22
22 of 22
Getting Counts...
Counting reads from fragments/bed file .. 
Correcting for GC bias...
Error in .checkTypos(e, names_x) : 
  Object 'per_chr_dist' not found amongst []
Calls: <Anonymous> ... <Anonymous> -> .checkTypos -> stopf -> raise_condition -> signal
In addition: Warning messages:
1: In fread(input) :
  Detected 1 column names but the data has 5 columns (i.e. invalid file). Added 4 extra default column names at the end.
2: In asMethod(object) :
  sparse->dense coercion: allocating vector of size 1.6 GiB
Execution halted
```

**Comment by KatharinaSchmid** [comment]
Hi Krithika,

The issue is very likely that you have zero windows after filtering. In the filtering step, all windows are removed that are 0 in more than 85% of the cells (this 85% is the default threshold, specified in the parameter `threshold_blacklist_bins`). I assume you didn't change this parameter `threshold_blacklist_bins`? In that case, it is strange, that all 26,088 windows are removed. But the cutoff you use for generating the count matrix `minFrags=500` is very low, so the danger is that your matrix is too sparse. Did you look at other quality controls for this dataset, e.g. the cellranger summary output? How is the coverage, the reads per cell? You could increase the window size for sparse datasets, but in the end, some datasets are probably too sparse for good quality CNV calls.

Best,
Katharina

**Comment by Krithika-Bhuvan** [comment]
thank you for the feedback.  I was able to run EpiAneufinder just fine using default settings. But we realized that the default value of minFrags=20,000 was filtering out 80% of cells .    I will test out the following settings based on your feedback. 
 * try to increase window size to 5e6 or 1e8,
 *  minFrags=1000 or 2000 or 3000
 * and see if that would work.

**Comment by Krithika-Bhuvan** [comment]
I had turned off the threshold_blacklist_bins filter in an effort to avoid filtering out too many cells , but that was causing the software to break. Once i set it back to threshold_blacklist_bins=0.85, I was able to get it working.
